### ISSUE TITLE
make node-app fails in Mac Yosemite

### ISSUE THREAD

**Issue by garviz** [qmachine/qmachine#7]
Hi,

I tried to install qmachine but it failed in Mac Yosemite.

make node-app
--> Created testpage.

> qm-node-app@1.2.4 prestart /Users/xxxx/qmachine/build/node-app
> node ./node_modules/qm/examples/roll-up.js

Saved to "katamari.json".

> qm-node-app@1.2.4 start /Users/xxxx/qmachine/build/node-app
> node server.js

/Users/xxxx/qmachine/build/node-app/node_modules/qm/node_modules/mongodb/lib/server.js:228
        process.nextTick(function() { throw err; })
                                            ^
Error
    at Object.<anonymous> (/Users/xxxxx/qmachine/build/node-app/node_modules/qm/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:42:24)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/xxxxx/qmachine/build/node-app/node_modules/qm/node_modules/mongodb/node_modules/mongodb-core/index.js:2:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! qm-node-app@1.2.4 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the qm-node-app@1.2.4 start script 'node server.js'.
npm ERR! This is most likely a problem with the qm-node-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls qm-node-app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/xxxx/qmachine/build/node-app/npm-debug.log

$ cat build/node-app/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose node symlink /usr/local/bin/node
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info prestart qm-node-app@1.2.4
7 verbose unsafe-perm in lifecycle true
8 info start qm-node-app@1.2.4
9 verbose unsafe-perm in lifecycle true
10 info qm-node-app@1.2.4 Failed to exec start script
11 verbose stack Error: qm-node-app@1.2.4 start: `node server.js`
11 verbose stack Exit status 1
11 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
11 verbose stack     at EventEmitter.emit (events.js:110:17)
11 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
11 verbose stack     at ChildProcess.emit (events.js:110:17)
11 verbose stack     at maybeClose (child_process.js:1008:16)
11 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
12 verbose pkgid qm-node-app@1.2.4
13 verbose cwd /Users/xxxx/qmachine/build/node-app
14 error Darwin 14.1.0
15 error argv "node" "/usr/local/bin/npm" "start"
16 error node v0.12.0
17 error npm  v2.5.1
18 error code ELIFECYCLE
19 error qm-node-app@1.2.4 start: `node server.js`
19 error Exit status 1
20 error Failed at the qm-node-app@1.2.4 start script 'node server.js'.
20 error This is most likely a problem with the qm-node-app package,
20 error not with npm itself.
20 error Tell the author that this fails on your system:
20 error     node server.js
20 error You can get their info via:
20 error     npm owner ls qm-node-app
20 error There is likely additional logging output above.
21 verbose exit [ 1, true ]

**Comment by wilkinson** [comment]
Thank you for letting me know! I apologize for the delay; I have been ill recently. My development machine runs Yosemite, so I'll take a look at this and get back to you!

**Comment by wilkinson** [comment]
Everything is working better on my machine now, and the tests are passing on Travis CI, too. Let me know how it goes on your end :-)
