### ISSUE TITLE
cardboards information

### ISSUE THREAD

**Issue by alexcostars** [qmachine/qmachine#8]
Hi @wilkinson,

when I utilize the API to get any informations about distributed processes, I have 2 options:

```
/v1/cardboard?key=982770f29
```

and

```
/v1/cardboard?status=waiting
```

But, can I know how much processes are waiting in current time (for all cardboards)?

**Comment by wilkinson** [comment]
No, it cannot be known. As you have noticed, you may only access an avar by a known `box` and a known `key`, or else by a known `box` and a known `status`. Both require a user to specify a known `box`; there is no way to query for all possible `box` values. This design provides a basic security model in which users may collaborate privately by sharing a `box` which is almost certain to be unused and unknown by anyone else -- especially if it is a [UUID](http://en.wikipedia.org/wiki/Universally_unique_identifier). The privacy of the `box` is therefore the responsibility of the users.

Thank you for asking. I will try to make this more clear in the [manual](https://docs.qmachine.org/en/latest/http-api.html) :-)

**Comment by alexcostars** [comment]
no no @wilkinson, it's clear in the manual.

I'm asking for this because we like to extract some statistics about current traffic (in real-time) in the QMachine Network (for a paper), but it's unnecessary.

Thank you for help
